name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: 2f4d5e4c-fb17-47a8-b024-b9a82d148f4d
          heroku_app_name: 'lexify-master'
          heroku_email: 'narendra.thapa@bitcanny.com'
